Rebase on Debian's 1.8.1-2 packaging, and cherry-pick system76-launch commit
pop-os/fwupd pull request #21
Opened 2022-07-01 16:48 UTC by ids1024

Updates fwupd to the latest release and cherry-picks the commit from https://github.com/fwupd/fwupd/pull/4767. We'll want to test that this addresses any issues flashing Launch, as well as general regression testing.

2022-07-02 03:05 UTC, 13r0ck approved these changes

2022-07-11 12:10 UTC, ahoneybun commented
New fwupd release with both this fix and `launch_2` support:

https://github.com/fwupd/fwupd/releases/tag/1.8.2

2022-07-11 18:59 UTC, 13r0ck requested changes
per @ahoneybun's comment, we should rebase on 1.8.2 now

2022-07-15 14:58 UTC, ids1024 commented
This is updated to Debian's 1.8.2-1 packaging, so it includes the Launch flashing fix without backporting that. We should verify that any issues with that are resolved.

Debian has also backported https://github.com/fwupd/fwupd/pull/4824, so we don't need a commit disabling capsule on disk. We may want to test that Dev One updates still work as expected.

2022-07-18 17:54 UTC, 13r0ck approved these changes

2023-05-05 14:21 UTC, closed without merging